'Initialize variables
Dim oAnsoftApp
Dim oDesktop
Dim oProject
Dim oDesign
Dim oEditor
Dim oModule

Dim Res_direction_var_value(40)
Dim Res_type_var_value(40)
Dim Res_total_length_var_value(40)
Dim Res_trace_width_var_value(40)
Dim Res_trace_gap_var_value(40)
Dim Res_x_spacing_var_value(40)
Dim Res_y_spacing_var_value(40)
Dim x_pos(40)
Dim y_pos(40)
Dim z_pos(40)
Dim direction_var(40)
Dim res_type(40)

'Set project objects
Set oAnsoftApp = CreateObject("AnsoftHfss.HfssScriptinterface")
Set oDesktop = oAnsoftApp.GetAppDesktop()
oDesktop.RestoreWindow
Set oProject = oDesktop.NewProject
Set oProject = oDesktop.GetActiveProject
oProject.InsertDesign "HFSS", "HFSSDesign1", "DrivenModal", ""

Set oDesign = oProject.GetActiveDesign
Set oEditor = oDesign.SetActiveEditor("3D Modeler")

oEditor.SetModelUnits Array("NAME:Units Parameter", "Units:=", "mil", "Rescale:=", _
false)

'STATIC VARIABLES
'Material Properties
core_L01_L02_material_name="RO3010"
core_L01_L02_dielectric_constant="10.2"
core_L01_L02_dielectric_loss_tangent="0.0022"
prepreg_L01_L02_material_name="2929"
prepreg_L01_L02_dielectric_constant="2.94"
prepreg_L01_L02_dielectric_loss_tangent="0.003"
core_L02_L03_material_name="RO3010" 
core_L02_L03_dielectric_constant="10.2"
core_L02_L03_dielectric_loss_tangent="0.0022"
cond_material_name="copper"
cond_bulk_conductivity="5.8e7"

Set oDefinitionManager = oProject.GetDefinitionManager()
oDefinitionManager.AddMaterial Array("NAME:"&core_L01_L02_material_name, "CoordinateSystemType:=", _
"Cartesian", Array("NAME:AttachedData"), "permittivity:=", _
core_L01_L02_dielectric_constant, "dielectric_loss_tangent:=", _
core_L01_L02_dielectric_loss_tangent)

oDefinitionManager.AddMaterial Array("NAME:"&prepreg_L01_L02_material_name, "CoordinateSystemType:=", _
"Cartesian", Array("NAME:AttachedData"), "permittivity:=", _
prepreg_L01_L02_dielectric_constant, "dielectric_loss_tangent:=", _
prepreg_L01_L02_dielectric_loss_tangent)

oDefinitionManager.AddMaterial Array("NAME:"&core_L02_L03_material_name, "CoordinateSystemType:=", _
"Cartesian", Array("NAME:AttachedData"), "permittivity:=", _
core_L02_L03_dielectric_constant, "dielectric_loss_tangent:=", _
core_L02_L03_dielectric_loss_tangent)

oDefinitionManager.AddMaterial Array("NAME:"&cond_material_name, "CoordinateSystemType:=", _
"Cartesian", Array("NAME:AttachedData"), Array("NAME:ModifierData"), _
"conductivity:=", cond_bulk_conductivity)

'Solution Setup
solution_freq_value = "10" 'Example center frequency in GHz
solution_freq = solution_freq_value & "GHz"
solution_freq_value_11 = solution_freq_value + 0.5 'Example delta
solution_freq_11 = solution_freq_value_11 & "GHz"
solution_freq_value_12 = solution_freq_value - 0.5
solution_freq_12 = solution_freq_value_12 & "GHz"

sweep_type = "Interpolating"
start_freq = "8GHz"
end_freq = "12GHz"
step_size = "0.01GHz"
max_delta_s = 0.01
num_passes = 40
percent_refine = 10

'Size Properties
Core_L01_L02_Height_value = 50 'mil example
Prepreg_L01_L02_Height_value = 10 
Core_L02_L03_Height_value = 50

cond_h_top_value = 0.7 
cond_h_trace_value = 0.7
cond_h_bottom_value = 0.7

Core_L01_L02_Height = Core_L01_L02_Height_value & "mil"
Prepreg_L01_L02_Height = Prepreg_L01_L02_Height_value & "mil"
Core_L02_L03_Height = Core_L02_L03_Height_value & "mil"

cond_h_top = cond_h_top_value & "mil"
cond_h_trace = cond_h_trace_value & "mil"
cond_h_bottom = cond_h_bottom_value & "mil"

'Get User Input
num_poles = 8

Edge_wall_pullback_value = 10
Wio_value = 20
Port_Width_value = 50
Lio_value = 100

Launch_orientation = 1 'Example
Launch_width_value = 15
Launch_spacing_value = 5

Edge_wall_pullback = Edge_wall_pullback_value & "mil"
Wio = Wio_value & "mil"
Port_Width = Port_Width_value & "mil"
Lio = Lio_value & "mil"
Launch_width = Launch_width_value & "mil"
Launch_spacing = Launch_spacing_value & "mil"
XYSpacing_Scale = 1

Res_direction_var_value(1) = 1
Res_direction_var_value(2) = 3
Res_direction_var_value(3) = 2
Res_direction_var_value(4) = 4
Res_direction_var_value(5) = 4
Res_direction_var_value(6) = 1
Res_direction_var_value(7) = 3
Res_direction_var_value(8) = 2

Res_type_var_value(1) = "A"
Res_type_var_value(2) = "B"
Res_type_var_value(3) = "B"
Res_type_var_value(4) = "A"
Res_type_var_value(5) = "A"
Res_type_var_value(6) = "B"
Res_type_var_value(7) = "B"
Res_type_var_value(8) = "A"

Res_total_length_var_value(1) = 200
Res_total_length_var_value(2) = 250 'Rectangular longer
Res_total_length_var_value(3) = 250
Res_total_length_var_value(4) = 200
Res_total_length_var_value(5) = 200
Res_total_length_var_value(6) = 250
Res_total_length_var_value(7) = 250
Res_total_length_var_value(8) = 200

Res_trace_width_var_value(1) = 10
Res_trace_width_var_value(2) = 10
Res_trace_width_var_value(3) = 10
Res_trace_width_var_value(4) = 10
Res_trace_width_var_value(5) = 10
Res_trace_width_var_value(6) = 10
Res_trace_width_var_value(7) = 10
Res_trace_width_var_value(8) = 10

Res_trace_gap_var_value(1) = 5
Res_trace_gap_var_value(2) = 5
Res_trace_gap_var_value(3) = 5
Res_trace_gap_var_value(4) = 5
Res_trace_gap_var_value(5) = 5
Res_trace_gap_var_value(6) = 5
Res_trace_gap_var_value(7) = 5
Res_trace_gap_var_value(8) = 5

Res_x_spacing_var_value(1) = 20
Res_x_spacing_var_value(2) = 5
Res_x_spacing_var_value(3) = 30
Res_x_spacing_var_value(4) = 15
Res_x_spacing_var_value(5) = 15
Res_x_spacing_var_value(6) = 30
Res_x_spacing_var_value(7) = 5
Res_x_spacing_var_value(8) = 20

Res_y_spacing_var_value(1) = 20
Res_y_spacing_var_value(2) = 30
Res_y_spacing_var_value(3) = 40
Res_y_spacing_var_value(4) = 25 'Example
Res_y_spacing_var_value(5) = 25
Res_y_spacing_var_value(6) = 40
Res_y_spacing_var_value(7) = 30
Res_y_spacing_var_value(8) = 20

Tap_location = "0mil"

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Tap_location", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Tap_location))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Launch_width", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Launch_width))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Launch_spacing", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Launch_spacing))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Edge_wall_pullback", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Edge_wall_pullback))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Wio", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Wio))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Port_Width", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Port_Width))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:Lio", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", Lio))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:ResonatorDeltaL", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", "0mil"))))

oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
"LocalVariables"), Array("NAME:NewProps", Array("NAME:XYSpacing_Scale", "PropType:=", "VariableProp", _
"UserDef:=", true, "Value:=", XYSpacing_Scale & ""))))

' Add variables for all Res parameters
For e = 1 To 8
  Res_direction = Res_direction_var_value(e) 
  oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
  "LocalVariables"), Array("NAME:NewProps", Array("NAME:Res_direction" & e, "PropType:=", "VariableProp", _
  "UserDef:=", true, "Value:=", Res_direction))))

  Res_total_length = Res_total_length_var_value(e) & "mil"
  oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
  "LocalVariables"), Array("NAME:NewProps", Array("NAME:Res_total_length" & e, "PropType:=", "VariableProp", _
  "UserDef:=", true, "Value:=", Res_total_length))))

  Res_trace_width = Res_trace_width_var_value(e) & "mil"
  oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
  "LocalVariables"), Array("NAME:NewProps", Array("NAME:Res_trace_width" & e, "PropType:=", "VariableProp", _
  "UserDef:=", true, "Value:=", Res_trace_width))))

  Res_trace_gap = Res_trace_gap_var_value(e) & "mil"
  oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
  "LocalVariables"), Array("NAME:NewProps", Array("NAME:Res_trace_gap" & e, "PropType:=", "VariableProp", _
  "UserDef:=", true, "Value:=", Res_trace_gap))))

  Res_x_spacing = Res_x_spacing_var_value(e) & "mil"
  oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
  "LocalVariables"), Array("NAME:NewProps", Array("NAME:Res_x_spacing" & e, "PropType:=", "VariableProp", _
  "UserDef:=", true, "Value:=", Res_x_spacing))))

  Res_y_spacing = Res_y_spacing_var_value(e) & "mil"
  oDesign.ChangeProperty Array("NAME:AllTabs", Array("NAME:LocalVariableTab", Array("NAME:PropServers", _
  "LocalVariables"), Array("NAME:NewProps", Array("NAME:Res_y_spacing" & e, "PropType:=", "VariableProp", _
  "UserDef:=", true, "Value:=", Res_y_spacing))))

Next

' Calculate positions
y_pos(1) = "0mil"
x_pos(1) = "- (Res_x_spacing1 * XYSpacing_Scale)/2"

For n = 2 To 4
  y_pos(n) = y_pos(n-1) & " - ((Res_total_length" & (n-1) & " + Res_trace_gap" & (n-1) & ") /4 + Res_trace_width" & (n-1) & ") - Res_y_spacing" & (n-1)
  x_pos(n) = x_pos(n-1) & " - (Res_x_spacing" & n & " * XYSpacing_Scale)/2"
Next

For n = 5 To 8
  k = 9 - n
  y_pos(n) = y_pos(k)
  x_pos(n) = "- (" & x_pos(k) & ")"
  direction_var(n) = IIf(direction_var(k) = 1, 2, IIf(direction_var(k) = 2, 1, direction_var(k)))
Next

For n = 1 To 8
  res_type(n) = Res_type_var_value(n)
  direction_var(n) = Res_direction_var_value(n)
  If n Mod 2 = 1 Then
    z_pos(n) = "0mil"
  Else
    z_pos(n) = "Prepreg_L01_L02_Height"
  End If
Next

Dim Cond_string
Cond_string = ""

Dim Bottom_Box_string
Bottom_Box_string = "0mil"

Dim Top_Box_string
Top_Box_string = "0mil"

Dim Left_Box_string
Left_Box_string = "0mil"

Dim Right_Box_string
Right_Box_string = "0mil"

For n = 1 To num_poles

  Res_side_length = "((Res_total_length" & n & " + Res_trace_gap" & n & ") /4 + Res_trace_width" & n & ")"

  If n = 1 Then
    Cond_string = "L02_1"
  Else
    Cond_string = Cond_string & ",L02_" & n
  End If

  Call CreateResonator(n, res_type(n), x_pos(n), y_pos(n), z_pos(n), direction_var(n))

  Bottom_Box_string = "min(" & Bottom_Box_string & ", " & y_pos(n) & " - " & Res_side_length & ")"

  Top_Box_string = "max(" & Top_Box_string & ", " & y_pos(n) & " + " & Res_side_length & ")"

  Left_Box_string = "min(" & Left_Box_string & ", " & x_pos(n) & " - " & Res_side_length & ")"

  Right_Box_string = "max(" & Right_Box_string & ", " & x_pos(n) & " + " & Res_side_length & ")"

Next

' Sweep for thickness
oEditor.SweepAlongVector Array("NAME:Selections", "Selections:=", Cond_string, "NewPartsModelFlag:=", _
"Model"), Array("NAME:VectorSweepParameters", "DraftAngle:=", "0deg", "DraftType:=", _
"Round", "CheckFaceFaceIntersection:=", false, "SweepVectorX:=", "0mm", "SweepVectorY:=", _
"0mm", "SweepVectorZ:=", "cond_h_trace")

' Create substrate layers
' Fix the prepreg Z to 0mil
'Create Bottom Core
oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", Left_Box_string & " - Edge_wall_pullback", _
"YPosition:=", Bottom_Box_string & " - Edge_wall_pullback", "ZPosition:=", "-Core_L02_L03_Height", "XSize:=", Right_Box_string & " - " & Left_Box_string & " + 2*Edge_wall_pullback", "YSize:=", _
Top_Box_string & " - " & Bottom_Box_string & " + 2*Edge_wall_pullback", "ZSize:=", "Core_L02_L03_Height"), Array("NAME:Attributes", "Name:=", _
"SUB_CORE_L02_L03_1", "Flags:=", "", "Color:=", _
"(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
"Global", "MaterialValue:=", "" & Chr(34) & core_L02_L03_material_name & Chr(34) & "", "SolveInside:=", _
true)

'Create Prepreg
oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", Left_Box_string & " - Edge_wall_pullback", _
"YPosition:=", Bottom_Box_string & " - Edge_wall_pullback", "ZPosition:=", "0mil", "XSize:=", Right_Box_string & " - " & Left_Box_string & " + 2*Edge_wall_pullback", "YSize:=", _
Top_Box_string & " - " & Bottom_Box_string & " + 2*Edge_wall_pullback", "ZSize:=", "Prepreg_L01_L02_Height"), Array("NAME:Attributes", "Name:=", _
"PREPREG_L01_L02_1", "Flags:=", "", "Color:=", _
"(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
"Global", "MaterialValue:=", "" & Chr(34) & prepreg_L01_L02_material_name & Chr(34) & "", "SolveInside:=", _
true)

'Create Top Core
oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", Left_Box_string & " - Edge_wall_pullback", _
"YPosition:=", Bottom_Box_string & " - Edge_wall_pullback", "ZPosition:=", "Prepreg_L01_L02_Height", "XSize:=", Right_Box_string & " - " & Left_Box_string & " + 2*Edge_wall_pullback", "YSize:=", _
Top_Box_string & " - " & Bottom_Box_string & " + 2*Edge_wall_pullback", "ZSize:=", "Core_L01_L02_Height"), Array("NAME:Attributes", "Name:=", _
"SUB_CORE_L01_L02_1", "Flags:=", "", "Color:=", _
"(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
"Global", "MaterialValue:=", "" & Chr(34) & core_L01_L02_material_name & Chr(34) & "", "SolveInside:=", _
true)

'Create Bottom Ground
oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", Left_Box_string & " - Edge_wall_pullback", _
"YPosition:=", Bottom_Box_string & " - Edge_wall_pullback", "ZPosition:=", "-Core_L02_L03_Height - cond_h_bottom", "XSize:=", Right_Box_string & " - " & Left_Box_string & " + 2*Edge_wall_pullback", "YSize:=", _
Top_Box_string & " - " & Bottom_Box_string & " + 2*Edge_wall_pullback", "ZSize:=", "cond_h_bottom"), Array("NAME:Attributes", "Name:=", _
"L03_1", "Flags:=", "", "Color:=", _
"(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
"Global", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
false)

'Create Top Ground
oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", Left_Box_string & " - Edge_wall_pullback", _
"YPosition:=", Bottom_Box_string & " - Edge_wall_pullback", "ZPosition:=", "Prepreg_L01_L02_Height + Core_L01_L02_Height", "XSize:=", Right_Box_string & " - " & Left_Box_string & " + 2*Edge_wall_pullback", "YSize:=", _
Top_Box_string & " - " & Bottom_Box_string & " + 2*Edge_wall_pullback", "ZSize:=", "cond_h_top"), Array("NAME:Attributes", "Name:=", _
"L01_1", "Flags:=", "", "Color:=", _
"(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
"Global", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
false)

' Launch structures
If Launch_orientation = 1 Then
  ' Left launch
  Dim left_launch_x, left_launch_y
  left_launch_x = x_pos(1) - "(Res_total_length1 + Res_trace_gap1)/4 + Res_trace_width1"
  left_launch_y = y_pos(1) - Res_side_length1 - "Launch_spacing" - "Wio/2"

  ' Example simple coupled launch, extend for complex meander
  oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", left_launch_x & " - Lio", "YPosition:=", _
  left_launch_y, "ZPosition:=", "0mil", "XSize:=", "Lio", "YSize:=", "Wio", "ZSize:=", _
  "cond_h_trace"), Array("NAME:Attributes", "Name:=", "Port_Trace1", "Flags:=", "", "Color:=", _
  "(132 132 193)", "Transparency:=", 0, "PartCoordinateSystem:=", _
  "Global", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
  false)

  ' Coupled section
  oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", left_launch_x, "YPosition:=", _
  left_launch_y, "ZPosition:=", "0mil", "XSize:=", "(Res_total_length1 + Res_trace_gap1)/4 + Res_trace_width1", "YSize:=", "Launch_width", "ZSize:=", _
  "cond_h_trace"), Array("NAME:Attributes", "Name:=", "Port_Trace1a", "Flags:=", "", "Color:=", _
  "(132 132 193)", "Transparency:=", 0, "PartCoordinateSystem:=", _
  "Global", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
  false)

  ' Unite launch parts
  oEditor.Unite Array("NAME:Selections", "Selections:=", "Port_Trace1,Port_Trace1a"), Array("NAME:UniteParameters", "KeepOriginals:=", false)

  ' Update bounding for launch
  Left_Box_string = "min(" & Left_Box_string & ", " & left_launch_x & " - Lio)"
  Bottom_Box_string = "min(" & Bottom_Box_string & ", " & left_launch_y & " - Launch_width)"

  ' Port1 rectangle
  oEditor.CreateRectangle Array("NAME:RectangleParameters", "IsCovered:=", true, "XStart:=", _
  left_launch_x & " - Lio", "YStart:=", left_launch_y & " - Port_Width/2 + Wio/2", "ZStart:=", "-Core_L02_L03_Height", "Width:=", "Port_Width", "Height:=", "Core_L02_L03_Height + Prepreg_L01_L02_Height + Core_L01_L02_Height + cond_h_top + cond_h_bottom", "WhichAxis:=", "Y"), Array("NAME:Attributes", "Name:=", "Port1", "Flags:=", "", "Color:=", _
  "(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
  "Global", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", false)

  ' Assign Port1
  oModule.AssignWavePort Array("NAME:Port1", "Objects:=", Array("Port1"), "NumModes:=", 1, "RenormalizeAllTerminals:=", true, "DoDeembed:=", true, "DeembedDist:=", "Lio", Array("NAME:Modes", Array("NAME:Mode1", "ModeNum:=", 1, "UseIntLine:=", true, Array("NAME:IntLine", "Start:=", Array(left_launch_x & " - Lio", left_launch_y & " + Wio/2", "-Core_L02_L03_Height"), "End:=", Array(left_launch_x & " - Lio", left_launch_y & " + Wio/2", "0mil")), "CharImp:=", "Zpi", "AlignmentGroup:=", 0, "RenormImp:=", "50ohm")), "ShowReporterFilter:=", false, "ReporterFilter:=", Array(true), "UseAnalyticAlignment:=", false)

  ' Similar for right launch, symmetric
  Dim right_launch_x, right_launch_y
  right_launch_x = x_pos(8) + "(Res_total_length8 + Res_trace_gap8)/4 + Res_trace_width8"
  right_launch_y = y_pos(8) - Res_side_length8 - "Launch_spacing" - "Wio/2"

  ' Right port_trace
  oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", right_launch_x, "YPosition:=", _
  right_launch_y, "ZPosition:=", "0mil", "XSize:=", "Lio", "YSize:=", "Wio", "ZSize:=", _
  "cond_h_trace"), Array("NAME:Attributes", "Name:=", "Port_Trace2", "Flags:=", "", "Color:=", _
  "(132 132 193)", "Transparency:=", 0, "PartCoordinateSystem:=", _
  "Global", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
  false)

  ' Coupled section
  oEditor.CreateBox Array("NAME:BoxParameters", "XPosition:=", right_launch_x - "(Res_total_length8 + Res_trace_gap8)/4 + Res_trace_width8", "YPosition:=", _
  right_launch_y, "ZPosition:=", "0mil", "XSize:=", "(Res_total_length8 + Res_trace_gap8)/4 + Res_trace_width8", "YSize:=", "Launch_width", "ZSize:=", _
  "cond_h_trace"), Array("NAME:Attributes", "Name:=", "Port_Trace2a", "Flags:=", "", "Color:=", _
  "(132 132 193)", "Transparency:=", 0, "PartCoordinateSystem:=", _
  "Global", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
  false)

  oEditor.Unite Array("NAME:Selections", "Selections:=", "Port_Trace2,Port_Trace2a"), Array("NAME:UniteParameters", "KeepOriginals:=", false)

  Right_Box_string = "max(" & Right_Box_string & ", " & right_launch_x & " + Lio)"

  Bottom_Box_string = "min(" & Bottom_Box_string & ", " & right_launch_y & " - Launch_width)"

  ' Port2 rectangle
  oEditor.CreateRectangle Array("NAME:RectangleParameters", "IsCovered:=", true, "XStart:=", _
  right_launch_x & " + Lio", "YStart:=", right_launch_y & " - Port_Width/2 + Wio/2", "ZStart:=", "-Core_L02_L03_Height", "Width:=", "Port_Width", "Height:=", "Core_L02_L03_Height + Prepreg_L01_L02_Height + Core_L01_L02_Height + cond_h_top + cond_h_bottom", "WhichAxis:=", "Y"), Array("NAME:Attributes", "Name:=", "Port2", "Flags:=", "", "Color:=", _
  "(132 132 193)", "Transparency:=", 0.8, "PartCoordinateSystem:=", _
  "Global", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", false)

  ' Assign Port2
  oModule.AssignWavePort Array("NAME:Port2", "Objects:=", Array("Port2"), "NumModes:=", 1, "RenormalizeAllTerminals:=", true, "DoDeembed:=", true, "DeembedDist:=", "Lio", Array("NAME:Modes", Array("NAME:Mode1", "ModeNum:=", 1, "UseIntLine:=", true, Array("NAME:IntLine", "Start:=", Array(right_launch_x & " + Lio", right_launch_y & " + Wio/2", "-Core_L02_L03_Height"), "End:=", Array(right_launch_x & " + Lio", right_launch_y & " + Wio/2", "0mil")), "CharImp:=", "Zpi", "AlignmentGroup:=", 0, "RenormImp:=", "50ohm")), "ShowReporterFilter:=", false, "ReporterFilter:=", Array(true), "UseAnalyticAlignment:=", false)

End If

' For Launch_orientation = 2, implement similar but adjusted for top ports

' Update substrates with full bounding
' Already done with min/max

' Unite substrates if multiple, but since one, no need

' Solution setup same as in the code

Set oModule = oDesign.GetModule("AnalysisSetup")
oModule.InsertSetup "HfssDriven", Array("NAME:Setup1", "Frequency:=", solution_freq, _
"PortsOnly:=", false, "MaxDeltaS:=", CDbl(max_delta_s), "UseMatrixConv:=", false, _
"MaximumPasses:=", num_passes, "MinimumPasses:=", 1, _
"MinimumConvergedPasses:=", 1, "PercentRefinement:=", percent_refine, "IsEnabled:=", _
true, "BasisOrder:=", 1, "DoLambdaRefine:=", true, "DoMaterialLambda:=", _
true, "SetLambdaTarget:=", false, "Target:=", 0.3333, "UseMaxTetIncrease:=", _
false, "PortAccuracy:=", 2, "UseABCOnPort:=", _
false, "SetPortMinMaxTri:=", false, "UseDomains:=", false, "UseIterativeSolver:=", _
false, "SaveRadFieldsOnly:=", false, "SaveAnyFields:=", true, "NoAdditionalRefinementOnImport:=", _
false)

oModule.InsertSetup "HfssDriven", Array("NAME:Setup1_0", "Frequency:=", solution_freq_11, "PortsOnly:=", _
false, "MaxDeltaS:=", 0.01, "UseMatrixConv:=", false, "MaximumPasses:=", 4, "MinimumPasses:=", _
1, "MinimumConvergedPasses:=", 1, "PercentRefinement:=", percent_refine, "IsEnabled:=", _
true, Array("NAME:MeshLink", "Project:=", "This Project*", "Design:=", "This Design*", "Soln:=", _
"Setup1 : LastAdaptive", Array("NAME:Params", "ForceSourceToSolve:=", false, "PreservePartnerSoln:=", _
false, "PathRelativeTo:=", "TargetProject", "ApplyMeshOp:=", false, "AdaptPort:=", _
false), "BasisOrder:=", 1, "DoLambdaRefine:=", false, "DoMaterialLambda:=", true, "SetLambdaTarget:=", _
false, "Target:=", 0.3333, "UseMaxTetIncrease:=", _
false, "PortAccuracy:=", 2, "UseABCOnPort:=", false, "SetPortMinMaxTri:=", _
false, "UseDomains:=", false, "UseIterativeSolver:=", false, "SaveRadFieldsOnly:=", _
false, "SaveAnyFields:=", true, "NoAdditionalRefinementOnImport:=", false)

oModule.InsertSetup "HfssDriven", Array("NAME:Setup1_1", "Frequency:=", solution_freq_12, "PortsOnly:=", _
false, "MaxDeltaS:=", 0.01, "UseMatrixConv:=", false, "MaximumPasses:=", 4, "MinimumPasses:=", _
1, "MinimumConvergedPasses:=", 1, "PercentRefinement:=", percent_refine, "IsEnabled:=", _
true, Array("NAME:MeshLink", "Project:=", "This Project*", "Design:=", "This Design*", "Soln:=", _
"Setup1_0 : LastAdaptive", Array("NAME:Params", "ForceSourceToSolve:=", false, "PreservePartnerSoln:=", _
false, "PathRelativeTo:=", "TargetProject", "ApplyMeshOp:=", false, "AdaptPort:=", _
false), "BasisOrder:=", 1, "DoLambdaRefine:=", false, "DoMaterialLambda:=", true, "SetLambdaTarget:=", _
false, "Target:=", 0.3333, "UseMaxTetIncrease:=", _
false, "PortAccuracy:=", 2, "UseABCOnPort:=", false, "SetPortMinMaxTri:=", _
false, "UseDomains:=", false, "UseIterativeSolver:=", false, "SaveRadFieldsOnly:=", _
false, "SaveAnyFields:=", true, "NoAdditionalRefinementOnImport:=", false)

oModule.InsertSetup "HfssDriven", Array("NAME:Setup1_2", "AdaptMultipleFreqs:=", true, _
Array("NAME:MultipleAdaptiveFreqsSetup", Array("NAME:Broadband", "Low:=", _
start_freq, "High:=", end_freq)), "MaxDeltaS:=", 0.01, "MaximumPasses:=", 10, "MinimumPasses:=", _
1, "MinimumConvergedPasses:=", 1, "PercentRefinement:=", 10, "IsEnabled:=", _
true, Array("NAME:MeshLink", "Project:=", "This Project*", "Design:=", "This Design*", "Soln:=", _
"Setup1_1 : LastAdaptive", Array("NAME:Params", "ForceSourceToSolve:=", false, "PreservePartnerSoln:=", _
false, "PathRelativeTo:=", "TargetProject", "ApplyMeshOp:=", false, "AdaptPort:=", _
false), "BasisOrder:=", 1, "DoLambdaRefine:=", false, "DoMaterialLambda:=", _
false, "SetLambdaTarget:=", false, "Target:=", 0.3333, "UseMaxTetIncrease:=", _
false, "PortAccuracy:=", 2, "UseABCOnPort:=", false, "SetPortMinMaxTri:=", _
false, "UseDomains:=", false, "UseIterativeSolver:=", true, "IterativeResidual:=", _
0.0001, "DDMSolverResidual:=", 0.0001, "SaveRadFieldsOnly:=", false, "SaveAnyFields:=", _
true, "IESolverType:=", "Auto", "LambdaTargetForIESolver:=", 0.15, "UseDefaultLambdaTgtForIESolver:=", _
true, "RayDensityPerWavelength:=", 4, "MaxNumberOfBounces:=", 5, "InfiniteSphereSetup:=", _
-1, "SkipSBRSolveDuringAdaptivePasses:=", false)

oModule.InsertFrequencySweep "Setup1_2", Array("NAME:Sweep1", "IsEnabled:=", true, "SetupType:=", _
"LinearStep", "StartValue:=", start_freq, "StopValue:=", end_freq, "StepSize:=", _
step_size, "Type:=", sweep_type, "SaveFields:=", false, "SaveRadFields:=", _
false, "InterpTolerance:=", 0.5, "InterpMaxSols:=", 250, "InterpMinSols:=", _
0, "InterpMinSubranges:=", 1, "ExtrapToDC:=", false, "InterpUseS:=", true, "InterpUsePortImped:=", _
false, "InterpUsePropConst:=", true, "UseDerivativeConvergence:=", false, "InterpDerivTolerance:=", _
0.2, "UseFullBasis:=", true, "EnforcePassivity:=", true, "PassivityErrorTolerance:=", _
0.0001)

'Turn on material override
oDesign.SetDesignSettings Array("NAME:Design Settings Data", "Allow Material Override:=", true)

' Sub for CreateResonator
Sub CreateResonator(res_num, res_type, x_pos, y_pos, z_pos, direction)
  Dim gap = "Res_trace_gap" & res_num
  Dim width = "Res_trace_width" & res_num
  Dim total_length = "Res_total_length" & res_num
  Res_side_length = "(( " & total_length & " + " & gap & " ) /4 + " & width & ")"

  If res_type = "B" Then
    ' For B, make rectangular, say longer in vertical, or dual gaps
    ' For dual, insert points for middle arm. Assume middle arm width = width, gaps = gap/2
    gap1 = gap & "/2"
    gap2 = gap & "/2"
    middle_width = width
    arm_top = "( " & Res_side_length & " - " & gap & " - " & middle_width & " ) /2"
    arm_bottom = arm_top
    ' For direction 1, example
    If direction = 1 Then
      oEditor.CreatePolyline Array("NAME:PolylineParameters", _
      "IsPolylineCovered:=", true, "IsPolylineClosed:=", _
      true, Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos & " + " & Res_side_length & "/2 + " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " + " & Res_side_length & "/2 + " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " - " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " + " & Res_side_length & " + " & width, "Y:=", y_pos & " - " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " + " & Res_side_length & " + " & width, "Y:=", y_pos & " + " & Res_side_length & " + " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " + " & Res_side_length & " + " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " - " & Res_side_length & "/2 - " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos & " - " & Res_side_length & "/2 - " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos & " - " & Res_side_length, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & Res_side_length, "Y:=", y_pos & " - " & Res_side_length, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & Res_side_length, "Y:=", y_pos, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos, "Z:=", z_pos)), _
      Array("NAME:PolylineSegments", _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2), _
      ... ' Add segments for all points
      ), Array("NAME:PolylineXSection", "XSectionType:=", _
      "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mm", "XSectionTopWidth:=", "0mm", "XSectionHeight:=", "0mm", "XSectionNumSegments:=", "0", "XSectionBendType:=", _
      "Corner")), Array("NAME:Attributes", "Name:=", "L02_" & res_num, "Flags:=", "", "Color:=", _
      "(132 132 193)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
      false)

  Else
    ' Single gap for type A
    ' Use the original polyline for direction
    If direction = 1 Then
      oEditor.CreatePolyline Array("NAME:PolylineParameters", _
      "IsPolylineCovered:=", true, "IsPolylineClosed:=", _
      true, Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos & " + " & Res_side_length & "/2 + " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " + " & Res_side_length & "/2 + " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " - " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " + " & Res_side_length & " + " & width, "Y:=", y_pos & " - " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " + " & Res_side_length & " + " & width, "Y:=", y_pos & " + " & Res_side_length & " + " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " + " & Res_side_length & " + " & width, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & width, "Y:=", y_pos & " - " & Res_side_length & "/2 - " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos & " - " & Res_side_length & "/2 - " & gap & "/2", "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos & " - " & Res_side_length, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & Res_side_length, "Y:=", y_pos & " - " & Res_side_length, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos & " - " & Res_side_length, "Y:=", y_pos, "Z:=", z_pos), _
      Array("NAME:PLPoint", "X:=", x_pos, "Y:=", y_pos, "Z:=", z_pos)), _
      Array("NAME:PolylineSegments", _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 1, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 2, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 3, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 4, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 5, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 6, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 7, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 8, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 9, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 10, "NoOfPoints:=", 2), _
      Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 11, "NoOfPoints:=", 2)), _
      Array("NAME:PolylineXSection", "XSectionType:=", _
      "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mm", _
      "XSectionTopWidth:=", _
      "0mm", "XSectionHeight:=", "0mm", "XSectionNumSegments:=", "0", _
      "XSectionBendType:=", _
      "Corner")), Array("NAME:Attributes", "Name:=", "L02_" & res_num, "Flags:=", "", "Color:=", _
      "(132 132 193)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & cond_material_name & Chr(34) & "", "SolveInside:=", _
      false)

    ElseIf direction = 2 Then
      ' Similar for other directions
      ' ...
    ElseIf direction = 3 Then
      ' ...
    ElseIf direction = 4 Then
      ' ...
    End If
  End If
End Sub

' For cancel
End If
End If
End If
End If
End If
